#### Import required libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, RobustScaler
import joblib

#### Load Dataset

In [ ]:
df_train = pd.read_csv("./dataset/CICDDOS_Train_Data.csv", low_memory=False)
df_test = pd.read_csv("./dataset/CICDDOS_Test_Data.csv", low_memory=False)

print("Dataset Loaded.")
print("Shape:", df_train.shape)
print("Shape:", df_test.shape)

Dataset Loaded.
Shape: (659455, 88)
Shape: (139900, 88)

#### Inspect Dataset Structure

In [131]:
df_train.head(3)

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,2911,172.16.0.5-192.168.50.1-634-37616-17,172.16.0.5,634,192.168.50.1,37616,17,2018-12-01 10:51:40.367822,36694,200,...,0.000000,0.0,0.0,0.00,0.000000,0.0,0.0,0,1,DrDoS_DNS
1,1417,172.16.0.5-192.168.50.1-634-587-17,172.16.0.5,634,192.168.50.1,587,17,2018-12-01 10:51:40.438699,38512,200,...,0.000000,0.0,0.0,0.00,0.000000,0.0,0.0,0,1,DrDoS_DNS
2,27,192.168.50.8-52.203.113.92-59165-443-6,192.168.50.8,59165,52.203.113.92,443,6,2018-12-01 10:51:43.453089,40022787,9,...,33.847698,59423.0,59349.0,9946250.25,112722.167135,10002623.0,9777167.0,0,0,BENIGN

In [133]:
df_test.head(3)

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,122219,172.16.0.5-192.168.50.4-648-31507-17,172.16.0.5,648,192.168.50.4,31507,17,2018-11-03 10:09:00.567188,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS
1,150058,172.16.0.5-192.168.50.4-1001-23378-17,172.16.0.5,1001,192.168.50.4,23378,17,2018-11-03 10:09:00.588081,47,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS
2,70873,172.16.0.5-192.168.50.4-674-26547-17,172.16.0.5,674,192.168.50.4,26547,17,2018-11-03 10:09:00.614656,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS

In [134]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 659455 entries, 0 to 659454
Data columns (total 88 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   659455 non-null  int64
 1   Flow ID                      659455 non-null  object
 2   Source IP                    659455 non-null  object
 3   Source Port                  659455 non-null  int64
 4   Destination IP               659455 non-null  object
 5   Destination Port             659455 non-null  int64
 6   Protocol                     659455 non-null  int64
 7   Timestamp                    659455 non-null  object
 8   Flow Duration                659455 non-null  int64
 9   Total Fwd Packets            659455 non-null  int64
 10  Total Backward Packets       659455 non-null  int64
 11  Total Length of Fwd Packets  659455 non-null  float64
 12  Total Length of Bwd Packets  659455 non-null  float64
 13  Fwd Packet Length Max        659455 non-null  float64
 14  Fwd Packet Length Min        659455 non-null  float64
 15  Fwd Packet Length Mean       659455 non-null  float64
 16  Fwd Packet Length Std        659455 non-null  float64
 17  Bwd Packet Length Max        659455 non-null  float64
 18  Bwd Packet Length Min        659455 non-null  float64
 19  Bwd Packet Length Mean       659455 non-null  float64
 20  Bwd Packet Length Std        659455 non-null  float64
 21  Flow Bytes/s                 646017 non-null  float64
 22  Flow Packets/s               659455 non-null  float64
 23  Flow IAT Mean                659455 non-null  float64
 24  Flow IAT Std                 659455 non-null  float64
 25  Flow IAT Max                 659455 non-null  float64
 26  Flow IAT Min                 659455 non-null  float64
 27  Fwd IAT Total                659455 non-null  float64
 28  Fwd IAT Mean                 659455 non-null  float64
 29  Fwd IAT Std                  659455 non-null  float64
 30  Fwd IAT Max                  659455 non-null  float64
 31  Fwd IAT Min                  659455 non-null  float64
 32  Bwd IAT Total                659455 non-null  float64
 33  Bwd IAT Mean                 659455 non-null  float64
 34  Bwd IAT Std                  659455 non-null  float64
 35  Bwd IAT Max                  659455 non-null  float64
 36  Bwd IAT Min                  659455 non-null  float64
 37  Fwd PSH Flags                659455 non-null  int64
 38  Bwd PSH Flags                659455 non-null  int64
 39  Fwd URG Flags                659455 non-null  int64
 40  Bwd URG Flags                659455 non-null  int64
 41  Fwd Header Length            659455 non-null  int64
 42  Bwd Header Length            659455 non-null  int64
 43  Fwd Packets/s                659455 non-null  float64
 44  Bwd Packets/s                659455 non-null  float64
 45  Min Packet Length            659455 non-null  float64
 46  Max Packet Length            659455 non-null  float64
 47  Packet Length Mean           659455 non-null  float64
 48  Packet Length Std            659455 non-null  float64
 49  Packet Length Variance       659455 non-null  float64
 50  FIN Flag Count               659455 non-null  int64
 51  SYN Flag Count               659455 non-null  int64
 52  RST Flag Count               659455 non-null  int64
 53  PSH Flag Count               659455 non-null  int64
 54  ACK Flag Count               659455 non-null  int64
 55  URG Flag Count               659455 non-null  int64
 56  CWE Flag Count               659455 non-null  int64
 57  ECE Flag Count               659455 non-null  int64
 58  Down/Up Ratio                659455 non-null  float64
 59  Average Packet Size          659455 non-null  float64
 60  Avg Fwd Segment Size         659455 non-null  float64
 61  Avg Bwd Segment Size         659455 non-null  float64
 62  Fwd Header Length.1          659455 non-null  int64
 63  Fwd Avg Bytes/Bulk           659455 non-null  int64
 64  Fwd Avg Packets/Bulk         659455 non-null  int64
 65  Fwd Avg Bulk Rate            659455 non-null  int64
 66  Bwd Avg Bytes/Bulk           659455 non-null  int64
 67  Bwd Avg Packets/Bulk         659455 non-null  int64
 68  Bwd Avg Bulk Rate            659455 non-null  int64
 69  Subflow Fwd Packets          659455 non-null  int64
 70  Subflow Fwd Bytes            659455 non-null  int64
 71  Subflow Bwd Packets          659455 non-null  int64
 72  Subflow Bwd Bytes            659455 non-null  int64
 73  Init_Win_bytes_forward       659455 non-null  int64
 74  Init_Win_bytes_backward      659455 non-null  int64
 75  act_data_pkt_fwd             659455 non-null  int64
 76  min_seg_size_forward         659455 non-null  int64
 77  Active Mean                  659455 non-null  float64
 78  Active Std                   659455 non-null  float64
 79  Active Max                   659455 non-null  float64
 80  Active Min                   659455 non-null  float64
 81  Idle Mean                    659455 non-null  float64
 82  Idle Std                     659455 non-null  float64
 83  Idle Max                     659455 non-null  float64
 84  Idle Min                     659455 non-null  float64
 85  SimillarHTTP                 659455 non-null  object
 86  Inbound                      659455 non-null  int64
 87  Label                        659455 non-null  object
dtypes: float64(45), int64(37), object(6)
memory usage: 442.7+ MB

In [135]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139900 entries, 0 to 139899
Data columns (total 88 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   139900 non-null  int64
 1   Flow ID                      139900 non-null  object
 2   Source IP                    139900 non-null  object
 3   Source Port                  139900 non-null  int64
 4   Destination IP               139900 non-null  object
 5   Destination Port             139900 non-null  int64
 6   Protocol                     139900 non-null  int64
 7   Timestamp                    139900 non-null  object
 8   Flow Duration                139900 non-null  int64
 9   Total Fwd Packets            139900 non-null  int64
 10  Total Backward Packets       139900 non-null  int64
 11  Total Length of Fwd Packets  139900 non-null  float64
 12  Total Length of Bwd Packets  139900 non-null  float64
 13  Fwd Packet Length Max        139900 non-null  float64
 14  Fwd Packet Length Min        139900 non-null  float64
 15  Fwd Packet Length Mean       139900 non-null  float64
 16  Fwd Packet Length Std        139900 non-null  float64
 17  Bwd Packet Length Max        139900 non-null  float64
 18  Bwd Packet Length Min        139900 non-null  float64
 19  Bwd Packet Length Mean       139900 non-null  float64
 20  Bwd Packet Length Std        139900 non-null  float64
 21  Flow Bytes/s                 139897 non-null  float64
 22  Flow Packets/s               139900 non-null  float64
 23  Flow IAT Mean                139900 non-null  float64
 24  Flow IAT Std                 139900 non-null  float64
 25  Flow IAT Max                 139900 non-null  float64
 26  Flow IAT Min                 139900 non-null  float64
 27  Fwd IAT Total                139900 non-null  float64
 28  Fwd IAT Mean                 139900 non-null  float64
 29  Fwd IAT Std                  139900 non-null  float64
 30  Fwd IAT Max                  139900 non-null  float64
 31  Fwd IAT Min                  139900 non-null  float64
 32  Bwd IAT Total                139900 non-null  float64
 33  Bwd IAT Mean                 139900 non-null  float64
 34  Bwd IAT Std                  139900 non-null  float64
 35  Bwd IAT Max                  139900 non-null  float64
 36  Bwd IAT Min                  139900 non-null  float64
 37  Fwd PSH Flags                139900 non-null  int64
 38  Bwd PSH Flags                139900 non-null  int64
 39  Fwd URG Flags                139900 non-null  int64
 40  Bwd URG Flags                139900 non-null  int64
 41  Fwd Header Length            139900 non-null  int64
 42  Bwd Header Length            139900 non-null  int64
 43  Fwd Packets/s                139900 non-null  float64
 44  Bwd Packets/s                139900 non-null  float64
 45  Min Packet Length            139900 non-null  float64
 46  Max Packet Length            139900 non-null  float64
 47  Packet Length Mean           139900 non-null  float64
 48  Packet Length Std            139900 non-null  float64
 49  Packet Length Variance       139900 non-null  float64
 50  FIN Flag Count               139900 non-null  int64
 51  SYN Flag Count               139900 non-null  int64
 52  RST Flag Count               139900 non-null  int64
 53  PSH Flag Count               139900 non-null  int64
 54  ACK Flag Count               139900 non-null  int64
 55  URG Flag Count               139900 non-null  int64
 56  CWE Flag Count               139900 non-null  int64
 57  ECE Flag Count               139900 non-null  int64
 58  Down/Up Ratio                139900 non-null  float64
 59  Average Packet Size          139900 non-null  float64
 60  Avg Fwd Segment Size         139900 non-null  float64
 61  Avg Bwd Segment Size         139900 non-null  float64
 62  Fwd Header Length.1          139900 non-null  int64
 63  Fwd Avg Bytes/Bulk           139900 non-null  int64
 64  Fwd Avg Packets/Bulk         139900 non-null  int64
 65  Fwd Avg Bulk Rate            139900 non-null  int64
 66  Bwd Avg Bytes/Bulk           139900 non-null  int64
 67  Bwd Avg Packets/Bulk         139900 non-null  int64
 68  Bwd Avg Bulk Rate            139900 non-null  int64
 69  Subflow Fwd Packets          139900 non-null  int64
 70  Subflow Fwd Bytes            139900 non-null  int64
 71  Subflow Bwd Packets          139900 non-null  int64
 72  Subflow Bwd Bytes            139900 non-null  int64
 73  Init_Win_bytes_forward       139900 non-null  int64
 74  Init_Win_bytes_backward      139900 non-null  int64
 75  act_data_pkt_fwd             139900 non-null  int64
 76  min_seg_size_forward         139900 non-null  int64
 77  Active Mean                  139900 non-null  float64
 78  Active Std                   139900 non-null  float64
 79  Active Max                   139900 non-null  float64
 80  Active Min                   139900 non-null  float64
 81  Idle Mean                    139900 non-null  float64
 82  Idle Std                     139900 non-null  float64
 83  Idle Max                     139900 non-null  float64
 84  Idle Min                     139900 non-null  float64
 85  SimillarHTTP                 139900 non-null  object
 86  Inbound                      139900 non-null  int64
 87  Label                        139900 non-null  object
dtypes: float64(45), int64(37), object(6)
memory usage: 93.9+ MB

In [136]:
df_train.describe()

d:\NewUser\Programs\miniconda3\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
d:\NewUser\Programs\miniconda3\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,Unnamed: 0,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Inbound
count,659455.000000,659455.000000,659455.000000,659455.000000,6.594550e+05,659455.000000,659455.000000,659455.000000,659455.000000,659455.000000,...,6.594550e+05,6.594550e+05,6.594550e+05,6.594550e+05,6.594550e+05,6.594550e+05,6.594550e+05,6.594550e+05,6.594550e+05,659455.000000
mean,97552.744298,24400.264946,32850.356625,15.114237,1.438022e+06,8.917503,0.067145,3873.925912,6.098446,622.124965,...,-3.982678e+07,1.003485e+03,7.545395e+02,2.022861e+03,5.776827e+02,4.171893e+05,9.208356e+04,5.227058e+05,3.361862e+05,0.997380
std,139332.467155,24853.427066,18913.030070,4.146729,9.494608e+06,251.582366,0.985513,11448.620661,834.314900,534.960901,...,2.018436e+08,5.964903e+04,3.561701e+04,8.861159e+04,5.484277e+04,2.871352e+06,8.586330e+05,3.626142e+06,2.431835e+06,0.051122
min,0.000000,0.000000,0.000000,0.000000,0.000000e+00,1.000000,0.000000,0.000000,0.000000,0.000000,...,-1.408238e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,14410.000000,767.000000,16491.000000,17.000000,1.000000e+00,2.000000,0.000000,458.000000,0.000000,229.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
50%,44636.000000,15249.000000,32867.000000,17.000000,1.000000e+00,2.000000,0.000000,1398.000000,0.000000,440.000000,...,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
75%,112545.500000,48910.000000,49254.000000,17.000000,1.510000e+02,4.000000,0.000000,2944.000000,0.000000,1376.000000,...,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
max,805181.000000,65532.000000,65535.000000,17.000000,1.200000e+08,99395.000000,287.000000,176000.000000,402076.000000,3491.000000,...,1.480000e+03,1.461992e+07,5.223460e+06,1.461992e+07,1.461992e+07,9.409758e+07,4.533786e+07,9.409758e+07,9.409758e+07,1.000000

In [137]:
df_test.describe()

d:\NewUser\Programs\miniconda3\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
d:\NewUser\Programs\miniconda3\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,Unnamed: 0,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Inbound
count,139900.000000,139900.000000,139900.000000,139900.000000,1.399000e+05,139900.000000,139900.000000,139900.000000,1.399000e+05,139900.000000,...,1.399000e+05,1.399000e+05,1.399000e+05,1.399000e+05,1.399000e+05,1.399000e+05,1.399000e+05,1.399000e+05,1.399000e+05,139900.000000
mean,144052.839979,23664.324496,32736.851015,14.084124,1.520773e+06,2.642130,0.372759,912.144274,9.156104e+01,404.214210,...,-3.156248e+07,4.430165e+03,6.288131e+03,1.278963e+04,8.413685e+02,4.412098e+05,1.317977e+05,5.839894e+05,3.163155e+05,0.994289
std,150041.230304,23576.742346,18933.688964,4.856200,9.087632e+06,24.660563,12.663943,1089.178028,2.261084e+04,456.175898,...,1.804055e+08,9.896627e+04,1.233760e+05,2.488632e+05,6.090374e+04,2.799071e+06,9.701208e+05,3.630437e+06,2.205147e+06,0.075357
min,1.000000,0.000000,0.000000,0.000000,0.000000e+00,1.000000,0.000000,0.000000,0.000000e+00,0.000000,...,-1.062719e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,32230.750000,784.000000,16388.000000,6.000000,1.000000e+00,2.000000,0.000000,60.000000,0.000000e+00,6.000000,...,8.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
50%,94146.000000,16966.500000,32782.000000,17.000000,1.000000e+00,2.000000,0.000000,458.000000,0.000000e+00,229.000000,...,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
75%,188143.500000,46110.000000,49069.500000,17.000000,4.800000e+01,2.000000,0.000000,1178.000000,0.000000e+00,426.000000,...,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
max,669955.000000,65531.000000,65535.000000,17.000000,1.198483e+08,8784.000000,4632.000000,52956.000000,8.419196e+06,3570.000000,...,1.480000e+03,1.400653e+07,2.135244e+07,4.553668e+07,8.304362e+06,6.285260e+07,3.362080e+07,6.878496e+07,6.285260e+07,1.000000

#### Label Normalization

In [50]:
label_map = {
    # BENIGN
    'BENIGN': 'BENIGN',

    # DrDoS => normalized
    'DrDoS_DNS': 'DNS',
    'DrDoS_LDAP': 'LDAP',
    'DrDoS_MSSQL': 'MSSQL',
    'DrDoS_NTP': 'NTP',
    'DrDoS_NetBIOS': 'NetBIOS',
    'DrDoS_SNMP': 'SNMP',
    'DrDoS_SSDP': 'SSDP',
    'DrDoS_UDP': 'UDP',

    # other label
    'DNS': 'DNS',
    'LDAP': 'LDAP',
    'MSSQL': 'MSSQL',
    'NetBIOS': 'NetBIOS',
    'NTP': 'NTP',
    'SNMP': 'SNMP',
    'SSDP': 'SSDP',
    'UDP': 'UDP',

    'UDP-lag': 'UDPLag',
    'UDPLag': 'UDPLag',
    'Syn': 'Syn',
    'TFTP': 'TFTP',
    'WebDDoS': 'WebDDoS',
    'Portmap': 'Portmap'
}

In [51]:
df_train['Label'] = df_train['Label'].map(label_map)
print("Train Data: ")
print(df_train['Label'].unique())
print(df_train['Label'].isnull().sum())

Train Data:
['DNS' 'BENIGN' 'LDAP' 'MSSQL' 'NetBIOS' 'NTP' 'SNMP' 'SSDP' 'UDP' 'Syn'
 'TFTP' 'UDPLag' 'WebDDoS']
0

In [52]:
df_test['Label'] = df_test['Label'].map(label_map)
print("Train Data: ")
print(df_test['Label'].unique())
print(df_test['Label'].isnull().sum())

Train Data:
['NetBIOS' 'BENIGN' 'LDAP' 'MSSQL' 'Portmap' 'Syn' 'UDP' 'UDPLag']
0

### Data Cleaning

#### Clean Column Names

In [53]:
print("Train Column : ", df_train.columns)

Train Column :  Index(['Unnamed: 0', 'Flow ID', 'Source IP', 'Source Port', 'Destination IP',
       'Destination Port', 'Protocol', 'Timestamp', 'Flow Duration',
       'Total Fwd Packets', 'Total Backward Packets',
       'Total Length of Fwd Packets', 'Total Length of Bwd Packets',
       'Fwd Packet Length Max', 'Fwd Packet Length Min',
       'Fwd Packet Length Mean', 'Fwd Packet Length Std',
       'Bwd Packet Length Max', 'Bwd Packet Length Min',
       'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s',
       'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max',
       'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std',
       'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean',
       'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags',
       'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length',
       'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s',
       'Min Packet Length', 'Max Packet Length', 'Packet Length Mean',
       'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count',
       'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count',
       'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio',
       'Average Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size',
       'Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk',
       'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', 'Subflow Fwd Bytes',
       'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward',
       'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean',
       'Idle Std', 'Idle Max', 'Idle Min', 'SimillarHTTP', 'Inbound', 'Label'],
      dtype='object')

In [54]:
print("Test Column : ", df_test.columns)

Test Column :  Index(['Unnamed: 0', 'Flow ID', 'Source IP', 'Source Port', 'Destination IP',
       'Destination Port', 'Protocol', 'Timestamp', 'Flow Duration',
       'Total Fwd Packets', 'Total Backward Packets',
       'Total Length of Fwd Packets', 'Total Length of Bwd Packets',
       'Fwd Packet Length Max', 'Fwd Packet Length Min',
       'Fwd Packet Length Mean', 'Fwd Packet Length Std',
       'Bwd Packet Length Max', 'Bwd Packet Length Min',
       'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s',
       'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max',
       'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std',
       'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean',
       'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags',
       'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length',
       'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s',
       'Min Packet Length', 'Max Packet Length', 'Packet Length Mean',
       'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count',
       'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count',
       'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio',
       'Average Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size',
       'Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk',
       'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', 'Subflow Fwd Bytes',
       'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward',
       'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean',
       'Idle Std', 'Idle Max', 'Idle Min', 'SimillarHTTP', 'Inbound', 'Label'],
      dtype='object')

#### Drop unnecessary columns

In [55]:
df_train.drop(columns=['Unnamed: 0'], inplace=True, errors='ignore')
df_test.drop(columns=['Unnamed: 0'], inplace=True, errors='ignore')

- fix the column name

In [ ]:
df_train.columns = df_train.columns.str.strip() # strip leading and trailing spaces
df_train.columns = df_train.columns.str.replace(" ", "_") # replace space by _

df_test.columns = df_test.columns.str.strip() 
df_test.columns = df_test.columns.str.replace(" ", "_") 

train_cols = set(df_train.columns)
test_cols = set(df_test.columns)

print(f"In Train but not Test: {train_cols - test_cols}")
print(f"In Test but not Train: {test_cols - train_cols}")
print(df_train.columns)

In Train but not Test: set()
In Test but not Train: set()
Index(['Flow_ID', 'Source_IP', 'Source_Port', 'Destination_IP',
       'Destination_Port', 'Protocol', 'Timestamp', 'Flow_Duration',
       'Total_Fwd_Packets', 'Total_Backward_Packets',
       'Total_Length_of_Fwd_Packets', 'Total_Length_of_Bwd_Packets',
       'Fwd_Packet_Length_Max', 'Fwd_Packet_Length_Min',
       'Fwd_Packet_Length_Mean', 'Fwd_Packet_Length_Std',
       'Bwd_Packet_Length_Max', 'Bwd_Packet_Length_Min',
       'Bwd_Packet_Length_Mean', 'Bwd_Packet_Length_Std', 'Flow_Bytes/s',
       'Flow_Packets/s', 'Flow_IAT_Mean', 'Flow_IAT_Std', 'Flow_IAT_Max',
       'Flow_IAT_Min', 'Fwd_IAT_Total', 'Fwd_IAT_Mean', 'Fwd_IAT_Std',
       'Fwd_IAT_Max', 'Fwd_IAT_Min', 'Bwd_IAT_Total', 'Bwd_IAT_Mean',
       'Bwd_IAT_Std', 'Bwd_IAT_Max', 'Bwd_IAT_Min', 'Fwd_PSH_Flags',
       'Bwd_PSH_Flags', 'Fwd_URG_Flags', 'Bwd_URG_Flags', 'Fwd_Header_Length',
       'Bwd_Header_Length', 'Fwd_Packets/s', 'Bwd_Packets/s',
       'Min_Packet_Length', 'Max_Packet_Length', 'Packet_Length_Mean',
       'Packet_Length_Std', 'Packet_Length_Variance', 'FIN_Flag_Count',
       'SYN_Flag_Count', 'RST_Flag_Count', 'PSH_Flag_Count', 'ACK_Flag_Count',
       'URG_Flag_Count', 'CWE_Flag_Count', 'ECE_Flag_Count', 'Down/Up_Ratio',
       'Average_Packet_Size', 'Avg_Fwd_Segment_Size', 'Avg_Bwd_Segment_Size',
       'Fwd_Header_Length.1', 'Fwd_Avg_Bytes/Bulk', 'Fwd_Avg_Packets/Bulk',
       'Fwd_Avg_Bulk_Rate', 'Bwd_Avg_Bytes/Bulk', 'Bwd_Avg_Packets/Bulk',
       'Bwd_Avg_Bulk_Rate', 'Subflow_Fwd_Packets', 'Subflow_Fwd_Bytes',
       'Subflow_Bwd_Packets', 'Subflow_Bwd_Bytes', 'Init_Win_bytes_forward',
       'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward',
       'Active_Mean', 'Active_Std', 'Active_Max', 'Active_Min', 'Idle_Mean',
       'Idle_Std', 'Idle_Max', 'Idle_Min', 'SimillarHTTP', 'Inbound', 'Label'],
      dtype='object')

#### Check Missing Values

In [57]:
print("Train dataset")
print(df_train.isnull().sum())
print("Total Null " , df_train.isnull().sum().sum())

Train dataset
Flow_ID             0
Source_IP           0
Source_Port         0
Destination_IP      0
Destination_Port    0
                   ..
Idle_Max            0
Idle_Min            0
SimillarHTTP        0
Inbound             0
Label               0
Length: 87, dtype: int64
Total Null  13438

In [58]:
print("Test dataset")
print(df_test.isnull().sum())
print("Total Null " , df_test.isnull().sum().sum())

Test dataset
Flow_ID             0
Source_IP           0
Source_Port         0
Destination_IP      0
Destination_Port    0
                   ..
Idle_Max            0
Idle_Min            0
SimillarHTTP        0
Inbound             0
Label               0
Length: 87, dtype: int64
Total Null  3

#### Handle Infinit Values

In [59]:
df_train.replace([np.inf, -np.inf], np.nan, inplace=True)
print("After replacing infinity:")
print("Total Null", df_train.isnull().sum().sum())

After replacing infinity:
Total Null 47918

In [60]:
df_test.replace([np.inf, -np.inf], np.nan, inplace=True)
print("After replacing infinity:")
print("Total Null", df_test.isnull().sum().sum())

After replacing infinity:
Total Null 12112

#### Handle Missing Values

In [61]:
# Median is better than mean for skewed network data.
numeric_columns = df_train.select_dtypes(include=[np.number]).columns

train_medians = df_train[numeric_columns].median()

In [62]:

df_train[numeric_columns] = df_train[numeric_columns].fillna(train_medians)
df_test[numeric_columns] = df_test[numeric_columns].fillna(train_medians)

In [63]:
print("Total Null Contains row in Train : ", df_train.isnull().sum().sum())
print("Total Null Contains row in Test : ", df_test.isnull().sum().sum())

Total Null Contains row in Train :  0
Total Null Contains row in Test :  0

#### Remove Duplicate Rows

In [64]:
print("Before removing duplicates:")
print("Train : " ,  df_train.shape , " Test : ", df_test.shape)
df_train.drop_duplicates(inplace=True)
df_test.drop_duplicates(inplace=True)
print("After removing duplicates:")
print("Train : " ,  df_train.shape , " Test : ", df_test.shape)

Before removing duplicates:
Train :  (659455, 87)  Test :  (139900, 87)
After removing duplicates:
Train :  (659455, 87)  Test :  (139895, 87)

### Feature Selection

#### Remove Constant columns
- Some features always contain the same value.
- These features are useless.

In [65]:
# find constand columns
constant_columns = []

for col in df_train.columns:
    if df_train[col].nunique() == 1:
        constant_columns.append(col)

print("Constant Columns: ", constant_columns)
# Constant Columns:  ['Bwd_PSH_Flags', 'Fwd_URG_Flags', 'Bwd_URG_Flags', 'FIN_Flag_Count', 'PSH_Flag_Count', 'ECE_Flag_Count',
#  'Fwd_Avg_Bytes/Bulk', 'Fwd_Avg_Packets/Bulk', 'Fwd_Avg_Bulk_Rate', 'Bwd_Avg_Bytes/Bulk', 'Bwd_Avg_Packets/Bulk', 'Bwd_Avg_Bulk_Rate']

Constant Columns:  ['Bwd_PSH_Flags', 'Fwd_URG_Flags', 'Bwd_URG_Flags', 'FIN_Flag_Count', 'PSH_Flag_Count', 'ECE_Flag_Count', 'Fwd_Avg_Bytes/Bulk', 'Fwd_Avg_Packets/Bulk', 'Fwd_Avg_Bulk_Rate', 'Bwd_Avg_Bytes/Bulk', 'Bwd_Avg_Packets/Bulk', 'Bwd_Avg_Bulk_Rate']

In [66]:
print("Before columns drop : ")
print("Train : " ,  df_train.shape , " Test : ", df_test.shape)
df_train.drop(columns=constant_columns, inplace=True)
df_test.drop(columns=constant_columns, inplace=True)
print("After columns drop: ")
print("Train : " ,  df_train.shape , " Test : ", df_test.shape)

Before columns drop :
Train :  (659455, 87)  Test :  (139895, 87)
After columns drop:
Train :  (659455, 75)  Test :  (139895, 75)

#### Remove Irrelevant Feature

- Flow ID, Source IP, Source Port, Destination IP, Destination Port: These features specify who was talking. If we train a model on these, the model will just memorize the IP addresses of the attackers in the CIC dataset rather than learning how the attack looks. It will fail on a new network.
- Timestamp: Decision trees cannot handle raw datetime strings easily, and an attack happens independently of the exact millisecond recorded in 2018.
- SimillarHTTP: Contains highly unstructured text or is mostly missing.
- 'Fwd_Header_Length.1' and 'Fwd_Header_Length' duplicate feature

In [67]:
columns_to_drop = ['Flow_ID', 'Source_IP', 'Source_Port', 'Destination_IP', 'Destination_Port', 'Timestamp', 'SimillarHTTP', 'Fwd_Header_Length.1']

print("Before columns drop : ")
print("Train : " ,  df_train.shape , " Test : ", df_test.shape)
# drop columns if available
df_train = df_train.drop(columns=[col for col in columns_to_drop if col in df_train.columns])
df_test = df_test.drop(columns=[col for col in columns_to_drop if col in df_test.columns])
print("After columns drop: ")
print("Train : " ,  df_train.shape , " Test : ", df_test.shape)

Before columns drop :
Train :  (659455, 75)  Test :  (139895, 75)
After columns drop:
Train :  (659455, 67)  Test :  (139895, 67)

### Label Encoding And Feature Scaling

#### Separate Features and Target

In [68]:
X_train = df_train.drop(columns=['Label'])
y_train = df_train['Label']
X_test = df_test.drop(columns=['Label'])
y_test = df_test['Label']

#### Encode Target Label

In [69]:
print("Train Lable : ", y_train.unique())
print("Null : ", y_train.isnull().sum())
print("Test Label : ", y_test.unique())
print("Null : ", y_test.isnull().sum())

Train Lable :  ['DNS' 'BENIGN' 'LDAP' 'MSSQL' 'NetBIOS' 'NTP' 'SNMP' 'SSDP' 'UDP' 'Syn'
 'TFTP' 'UDPLag' 'WebDDoS']
Null :  0
Test Label :  ['NetBIOS' 'BENIGN' 'LDAP' 'MSSQL' 'Portmap' 'Syn' 'UDP' 'UDPLag']
Null :  0

- keep only common label

In [70]:
common_labels = y_train.unique()

mask = y_test.isin(common_labels)
X_test = X_test[mask]
y_test = y_test[mask]
X_test.shape, y_test.shape

((120199, 66), (120199,))

#### Label Encoding

In [71]:
#[WARNING ONLY FOR TRAINDATA] Only for Train Data [not for test]
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
label_encoder.classes_

array(['BENIGN', 'DNS', 'LDAP', 'MSSQL', 'NTP', 'NetBIOS', 'SNMP', 'SSDP',
       'Syn', 'TFTP', 'UDP', 'UDPLag', 'WebDDoS'], dtype=object)

In [72]:
y_train = pd.Series(label_encoder.transform(y_train), index=X_train.index, name='Label')
y_test = pd.Series(label_encoder.transform(y_test), index=X_test.index, name='Label')

In [73]:
joblib.dump(label_encoder, "./models/LabelEncoder.pkl")

['./models/LabelEncoder.pkl']

#### Scale the Features

In [ ]:
# Only For Train data [not for test]
# scaler = RobustScaler()

# scaler.fit(X_train)

RobustScaler()

In [ ]:
# X_train_scaled = scaler.transform(X_train)
# X_test_scaled = scaler.transform(X_test)

In [ ]:
# joblib.dump(scaler, "./models/scaler.pkl")

['./models/scaler.pkl']

In [ ]:
# X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
# X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)

# X_train_scaled.shape, X_test_scaled.shape

((659455, 66), (120199, 66))

#### Recombine Dataset and Save

In [74]:
# df_train = pd.concat([X_train_scaled, y_train], axis=1)
df_train['Label'] = y_train
print("Befor : ", df_train.shape, df_train.isnull().sum().sum())
df_train.dropna(inplace=True)
print("After : ", df_train.shape, df_train.isnull().sum().sum())

Befor :  (659455, 67) 0
After :  (659455, 67) 0

In [75]:
# df_test = pd.concat([X_test_scaled, y_test], axis=1)
df_test['Label'] = y_test
print("Befor : ", df_test.shape, df_test.isnull().sum().sum())
df_test.dropna(inplace=True)
print("After : ", df_test.shape, df_test.isnull().sum().sum())

Befor :  (139895, 67) 19696
After :  (120199, 67) 0

#### handles outliers

In [87]:
df_train.replace([np.inf, -np.inf], np.nan, inplace=True)
df_test.replace([np.inf, -np.inf], np.nan, inplace=True)
X_train = X_train.clip(-1e6, 1e6)
X_test = X_test.clip(-1e6, 1e6)
df_train.isnull().sum().sum()
df_test.isnull().sum().sum()

np.int64(0)

#### Save Datasete

In [76]:
df_train.to_csv("./dataset/Clean_CICDDOS_Train.csv", index=False)
print("Train datset saved successfully")

Train datset saved successfully

In [77]:
df_test.to_csv("./dataset/Clean_CICDDOS_Test.csv", index=False) 
print("Test datset saved successfully")

Test datset saved successfully

In [79]:
constant_cols = [col for col in X_train.columns if X_train[col].nunique() <= 1]
print(f"Removing {len(constant_cols)} constant columns: {constant_cols}")

Removing 0 constant columns: []

In [81]:
# Create correlation matrix
corr_matrix = X_train.corr().abs()

# Select upper triangle of correlation matrix
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

# Find features with correlation greater than 0.95
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]
print(f"Dropping {len(to_drop)} highly correlated features.")
print(to_drop)

Dropping 29 highly correlated features.
['Fwd_Packet_Length_Min', 'Fwd_Packet_Length_Mean', 'Bwd_Packet_Length_Std', 'Flow_IAT_Std', 'Flow_IAT_Max', 'Fwd_IAT_Total', 'Fwd_IAT_Mean', 'Fwd_IAT_Std', 'Fwd_IAT_Max', 'Fwd_IAT_Min', 'Bwd_IAT_Std', 'Bwd_IAT_Max', 'Fwd_Packets/s', 'Min_Packet_Length', 'Max_Packet_Length', 'Packet_Length_Mean', 'RST_Flag_Count', 'ACK_Flag_Count', 'Average_Packet_Size', 'Avg_Fwd_Segment_Size', 'Avg_Bwd_Segment_Size', 'Subflow_Fwd_Packets', 'Subflow_Fwd_Bytes', 'Subflow_Bwd_Packets', 'Subflow_Bwd_Bytes', 'act_data_pkt_fwd', 'Idle_Mean', 'Idle_Max', 'Idle_Min']

In [83]:
df_train.isin([np.inf, -np.inf]).sum().sum()

np.int64(0)